// TypeScript requires enum to be in a separate file as they are not treat as types or modules (incredibly annoying)

export enum ObjectTypes {
    addressForm = 'Address Form',
    advancedpdftemplate = 'Advanced PDF HTML Template',
    bundleinstallationscript = 'Bundle Installation Script',
    center = 'Center',
    centercategory = 'Center Category',
    centerlink = 'Center Link',
    centertab = 'Center Tab',
    clientscript = 'Client Script',
    customlist = 'Custom List',
    customrecordactionscript = 'Custom Record Action Script',
    customrecordtype = 'Custom Record Type',
    customsegment = 'Custom Segment',
    customtransactiontype = 'Custom Transaction Type',
    dataset = 'Dataset',
    emailtemplate = 'Email Template',
    entitycustomfield = 'Entity Custom Field',
    entryForm = 'Entry Form',
    integration = 'Integration',
    itemcustomfield = 'Item Custom Field',
    itemnumbercustomfield = 'Item Number Custom Field',
    itemoptioncustomfield = 'Item Option Custom Field',
    kpiscorecard = 'KPI Scorecard',
    mapreducescript = 'Map Reduce Script',
    massupdatescript = 'Mass Update Script',
    othercustomfield = 'Other Custom Field',
    portlet = 'Portlet',
    restlet = 'RESTlet',
    role = 'Role',
    savedcsvimport = 'Saved CSV Import',
    savedsearch = 'Saved Search',
    scheduledscript = 'Scheduled Script',
    sdfinstallationscript = 'SDF Installation Script',
    secret = 'API Secrets',
    sublist = 'Sublist',
    subtab = 'Subtab',
    suitelet = 'Suitelet',
    transactionform = 'Transaction Form',
    transactionbodycustomfield = 'Transaction Body Custom Field',
    transactioncolumncustomfield = 'Transaction Column Custom Field',
    usereventscript = 'User Event Script',
    workflow = 'Workflow',
    workflowactionscript = 'Workflow Action Script',
}